blogproject/blog/urls.py
# encoding: utf-8

'''
@author: siar
@contact: xzt1357@gmail.com
@file: urls.py
@time: 2017/6/21 11:06
@desc:
'''

from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^post/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blogproject/comments/urls.py
# encoding: utf-8
from django.conf.urls import url
from . import views


'''
@author: siar
@contact: xzt1357@gmail.com
@file: urls.py
@time: 2017/6/28 16:14
@desc:
'''

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment')
]

blogproject/blog/models.py
# coding:utf-8

from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
import markdown
from django.utils.html import strip_tags
from django.db.models.aggregates import Count
# Create your models here.
# 默认创建表格的时候，Django会自动创建id字段，无需在model中手动声明
# 使用装饰器decorator，修饰类
# 更改模型中的内容，添加字段，需要迁移数据库，让Django将更改反应到数据库中；添加方法或者内部类的话则不需要进行迁移
# env虚拟环境下：
# python manage.py makemigrations
# python manage.py migrate


@python_2_unicode_compatible
class Category(models.Model):
    """
    分类
    """
    # 分类名称
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    """
    标签
    """
    # 标签名称
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    """
    文章
    """
    # 文章标题 短字符串
    title = models.CharField(max_length=70)

    # 文章正文，字段类型TextField
    body = models.TextField()

    # 文章创建时间和最后一次修改时间，字段类型DateTimeField
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以为空，只需设置blank=True即可，否则为空时会报错
    excerpt = models.CharField(max_length=200, blank=True)

    # 关联文章与分类、标签，实际是按照自动创建的id来进行关联
    # 一篇文章只能对应一个分类，一个分类下有多篇文章  1:n  ForeignKey 一对多关联关系 外键关联
    # 一篇文章可以有多个标签，同一个标签下可以有多篇文章， m:n  ManyToManyField 多对多关联关系  中间表post.id-tag.id关联
    # 规定文章可以没有标签，即设置tags blank=True
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    # 导入Django内置应用django.contrib.auth.models里的User model
    # 一篇文章只能有一个作者，一个作者可以写多篇文章，1:n ForeignKey 一对多关联关系
    author = models.ForeignKey(User)

    # 新增views字段记录阅读量 类型为PositiveIntegerField, 该类型的值只允许为正整数或0，设定初始值为0
    views = models.PositiveIntegerField(default=0)

    # 自定义方法，当访问某篇文章时，post中的views字段值+1，然后调用save方法将更改后的值保存到数据库，保存时指定字段，只更新views
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    # 从django.urls 导入 reverser函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

    # 复写model.save方法
    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 实例化markdown类，用来渲染body正文
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将markdown文本渲染成HTML文本
            # strip_tags 去掉HTML文本的全部HTML标签
            # 从文本中摘取前54个字符赋给摘要excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        # 调用父类model的save方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

blogproject/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse
from .models import Post, Category, Tag
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q


# Create your views here.
# 主页视图
def index(request):
    # return HttpResponse("欢迎访问我的博客首页！")
    # return render(request, 'blog/index.html', context={
    #     'title': '我的博客首页',
    #     'welcome': '欢迎访问我的博客首页',
    # })
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 类视图中,ListView已经做好了分页逻辑,我们只需指定paginate_by属性来开启分页功能即可
# 使用类视图IndexView替代视图函数index
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    # 指定paginate_by 属性开启分页功能，其值表示每一页包含多少篇文章
    paginate_by = 3

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     paginator = context.get('paginator')
    #     page = context.get('page_obj')
    #     is_paginated = context.get('is_paginated')
    #
    #
    # def pagination_data(self, paginator, page, is_paginated):
    #     if not is_paginated:
    #         return {}
    #     left = []
    #     right = []
    #     left_has_more = False
    #     right_has_more = False
    #     first = False
    #     last = False
    #     page_number = page.number
    #     total_pages = paginator.num_pages
    #     page_range = paginator.page_range
    #     if page_number == 1:
    #         right = page_range[page_number: page_number + 2]


# 文章详情页视图
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # return render(request, 'blog/detail.html', context={'post': post})
    # 阅读量+1
    post.increase_views()
    # # 使用markdown语法渲染body，并支持代码格式扩展，代码语法高亮等
    # post.body = markdown.markdown(post.body, extensions=[
    #     'markdown.extensions.extra',
    #     'markdown.extensions.codehilite',
    #     'markdown.extensions.toc',
    # ])
    # 实例化一个Markdown对象，可以给post动态添加toc属性
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        # 处理目录的锚点显示问题
        TocExtension(slugify=slugify),
        # 'markdown.extensions.toc',
        ])
    post.body = md.convert(post.body)
    post.toc = md.toc

    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {
        'post': post,
        'form': form,
        'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context=context)


# 使用类视图PostDetailView替代视图函数detail
# PostDetailView 继承 DetailView，需求是从数据库中获取模型(Post)一条记录数据
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    # 复写父类的get方法，将post对象取出来，调用increase_views()，阅读量+1
    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        # self.object即为父类的get方法查询出来的Post类的对象实例
        self.object.increase_views()
        # 返回的是个HttpResponse对象
        return response

    # 对post对象的body进行markdown渲染
    # extensions参数
    # 'markdown.extensions.codehilite' 代码高亮拓展
    # 'markdown.extensions.toc' 自动生成目录的扩展
    # 这种直接调用markdown方法渲染post.body方法局限性在于只能通过[TOC]标记在文章内容中插入目录，而不能在页面其他地方插入。
    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        post.body = markdown.markdown(post.body,
                                      extensions=[
                                        'markdown.extensions.extra',
                                        'markdown.extensions.codehilite',
                                        'markdown.extensions.toc',
                                        ])
        return post

    # 将commentform评论表单、post下的评论列表传递给模板
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context

    def get_queryset(self):
        return super(PostDetailView, self).get_queryset()


# 归档详情页视图
def archives(request, year, month):
    """
    点击某个归档时间，显示此归档时间下的文章列表
    :param request:
    :param year:
    :param month:
    :return:
    """
    post_list = Post.objects.filter(created_time__year=year, created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 使用类视图ArchivesView替代视图函数archives
class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year, created_time__month=month)


# 分类详情页视图
def category(request, pk):
    """
    点击某个分类，显示此分类下的文章列表
    :param request:
    :param pk:
    :return: 此分类下的文章列表
    """
    cate = get_object_or_404(Category, pk=pk)
    # post_list = cate.post_set.all().order_by('-created_time')
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 使用类视图CategoryView替代视图函数category
class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# 使用类视图TagView显示某个标签下的文章列表
class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = "请输入关键字"
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg, 'post_list': post_list})

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="{{ post.get_absolute_url }}"><time class="entry-date"
                                                                      datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <!--文章内容-->
                        {{ post.body|safe }}
                        <div class="widget-tag-cloud">
                            <ul>
                                标签：
                                {% for tag in post.tags.all %}
                                    <li><a href="{% url 'blog:tag' tag.pk %}">#{{ tag.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                      {% csrf_token %}
                      <div class="row">
                        <div class="col-md-4">
                          <label for="{{ form.name.id_for_label }}">名字：</label>
                          {{ form.name }}
                          {{ form.name.errors }}
                        </div>
                        <div class="col-md-4">
                          <label for="{{ form.email.id_for_label }}">邮箱：</label>
                          {{ form.email }}
                          {{ form.email.errors }}
                        </div>
                        <div class="col-md-4">
                          <label for="{{ form.url.id_for_label }}">URL：</label>
                          {{ form.url }}
                          {{ form.url.errors }}
                        </div>
                        <div class="col-md-12">
                          <label for="{{ form.text.id_for_label }}">评论：</label>
                          {{ form.text }}
                          {{ form.text.errors }}
                          <button type="submit" class="comment-btn">发表</button>
                        </div>
                      </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <a href="#comment-area"></a>
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                            <ul class="comment-list list-unstyled">
                              {% for comment in comment_list %}
                              <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date">{{ comment.created_time }}</time>
                                <div class="text">
                                  {{ comment.text }}
                                </div>
                              </li>
                              {% empty %}
                              暂无评论
                              {% endfor %}
                            </ul>
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <!-- safe标签防止Django对HTML代码进行转义-->
        {{ post.toc|safe }}
    </div>
{% endblock toc%}

blogproject/templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
                {% for post in post_list %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <!--p标签显示的摘要-->
                        <p>{{ post.excerpt}}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}
                <!--使用ListView自带的分页-->
                {% if is_paginated %}
                <div class="pagination-simple">
                    <!-- 如果当前页还有上一页，则显示"上一页"按钮-->
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}
                    <!-- 显示当前页面信息 -->
                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                    <!-- 如果当前页还有下一页，则显示"下一页"按钮 -->
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                {% endif %}

                <!--<div class="pagination">-->
                    <!--<ul>-->
                        <!--<li><a href="">1</a></li>-->
                        <!--<li><a href="">...</a></li>-->
                        <!--<li><a href="">4</a></li>-->
                        <!--<li><a href="">5</a></li>-->
                        <!--<li class="current"><a href="">6</a></li>-->
                        <!--<li><a href="">7</a></li>-->
                        <!--<li><a href="">8</a></li>-->
                        <!--<li><a href="">...</a></li>-->
                        <!--<li><a href="">11</a></li>-->
                    <!--</ul>-->
                <!--</div>-->
{% endblock main %}