blogproject/blog/urls.py
# encoding: utf-8

'''
@author: siar
@contact: xzt1357@gmail.com
@file: urls.py
@time: 2017/6/21 11:06
@desc:
'''

from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^post/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
]

blogproject/comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible


# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blogproject/templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}
            <article class="post post-{{ result.object.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' result.object.category.pk %}">{{ result.object.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                datetime="{{ result.object.created_time }}">{{ result.object.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                            <span class="comments-link"><a href="{{ result.object.get_absolute_url }}#comment-area">{{ result.object.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <!--p标签显示的摘要-->
                        <p>{% highlight result.object.excerpt with query %}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div class="no-post">没有搜索到你想要的结果！</div>
                {% endfor %}
                 <!--使用ListView自带的分页-->
                {% if is_paginated %}
                <div class="pagination-simple">
                    <!-- 如果当前页还有上一页，则显示"上一页"按钮-->
                    {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                    {% endif %}
                    <!-- 显示当前页面信息 -->
                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
                    <!-- 如果当前页还有下一页，则显示"下一页"按钮 -->
                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                    {% endif %}
                </div>
                {% endif %}
    {% else %}
        请输入搜索关键字，例如 Django
    {% endif %}
{% endblock main %}